# render.yaml
# This file is used to configure the Render service for the Ohmi Audit application.
services:
  - type: web
    name: ohmi-audit-docker
    runtime: docker
    dockerfile: Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ohmi-audit-db  # Reuse existing DB
          property: connectionString
      - key: DOCKER
        value: "False"  # Set to False for Render environment
      - key: DEBUG
        value: "True"
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /health/
    disk:
      name: media_volume
      mountPath: /app/media_files
      sizeGB: 1  # Start with 1GB, increase as needed

  - type: worker
    name: celery-worker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ohmi-audit-db
          property: connectionString
      - key: USE_CELERY
        value: "True"
      - key: REDIS_URL
        value: "redis://redis:6379/0"
    command: celery -A ohmi_audit worker --loglevel=info