# Generated by Django 5.0.3 on 2025-06-18 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_customer_audit_created_at_audit_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audit',
            options={'ordering': ['id'], 'verbose_name': 'Audit', 'verbose_name_plural': 'Audits'},
        ),
        migrations.AlterModelOptions(
            name='auditor',
            options={'ordering': ['id'], 'verbose_name': 'Auditor', 'verbose_name_plural': 'Auditors'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['id'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AddField(
            model_name='audit',
            name='category',
            field=models.CharField(blank=True, choices=[('compliance', 'Compliance'), ('information_security', 'Information Security'), ('health_and_safety', 'Health and Safety'), ('other', 'Other')], default='other', max_length=255),
        ),
        migrations.AlterField(
            model_name='audit',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='audit',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='auditor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='auditor',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
