# Generated by Django 5.0.3 on 2025-06-19 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_audit_slug_auditor_slug_customer_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditAuditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('is_lead_auditor', models.BooleanField(default=False, help_text='Indicates if the auditor is the lead auditor for this audit')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_assignments', to='main_app.audit')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_assignments', to='main_app.auditor')),
            ],
            options={
                'verbose_name': 'Audit Assignment',
                'verbose_name_plural': 'Audit Assignments',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.AddField(
            model_name='audit',
            name='related_auditors',
            field=models.ManyToManyField(blank=True, related_name='audits', through='main_app.AuditAuditor', to='main_app.auditor'),
        ),
        migrations.AddConstraint(
            model_name='auditauditor',
            constraint=models.UniqueConstraint(fields=('audit', 'auditor'), name='unique_audit_auditor'),
        ),
    ]
