# Generated by Django 5.0.3 on 2025-06-19 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auditauditor_audit_related_auditors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='related_auditors',
        ),
        migrations.DeleteModel(
            name='AuditAuditor',
        ),
    ]
