# Generated by Django 5.0.3 on 2025-06-19 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auditauditor_audit_related_auditors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditauditor',
            name='audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditor_assignments', to='main_app.audit'),
        ),
        migrations.AlterField(
            model_name='auditauditor',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_assignments', to='main_app.auditor'),
        ),
    ]
