# Generated by Django 5.0.3 on 2025-06-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_audit_related_auditors_delete_auditauditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='audit_images/'),
        ),
    ]
