# Generated by Django 5.0.3 on 2025-06-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_audit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='audit_files/'),
        ),
    ]
